sonar.projectKey=23suca01-svg_vehiclemanagementfrontend
sonar.organization=23suca01-svg

sonar.sourceEncoding=UTF-8

# coverage file
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# EXCLUDE FILES FROM COVERAGE
sonar.coverage.exclusions=src/App.js,src/index.js,src/components/VehicleForm.js,src/services/**